server:
  port: 8080
  mode: debug

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: demo_db_user
  password: demoAbc123
  dbname: demo_db
  charset: utf8mb4
  parseTime: true
  loc: Local

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

log:
  level: info
  filename: app.log
  maxsize: 100
  maxage: 30
  maxbackups: 10